#!/usr/bin/env bash
# Scored run: keep launching Harbor waves until every task in the seeded order has 4 valid attempts.
#   setsid nohup ./wave_loop.sh <lane> > ../../logs/lane<lane>.log 2>&1 &     (run lanes 1 and 2: 30 sandboxes each)
# Resumable: task need = 4 - valid attempts across jobs/wave-*; tasks claimed by a running wave are skipped.
# Stops when $HERE/STOP exists. Do not edit this file while it runs.
set -uo pipefail
LANE=$1
HERE=/home/charlieruan/mimo; SRC=$HERE/rl-env-cleaner/mimo_swe; cd $HERE
ORDER=$HERE/task_order_seed20261006.txt
WAVE=${WAVE:-60}; NC=${NC:-30}; MAX_INFRA=${MAX_INFRA:-6}
PY=$HOME/.local/share/uv/tools/harbor/bin/python
mkdir -p claims waves
touch excluded_infra.txt
while [ ! -e STOP ]; do
  if ! $SRC/endpoint_health.sh; then echo "$(date -Is) lane$LANE endpoint down; waiting"; sleep 60; continue; fi
  exec 9>claims/.lock; flock 9
  rm -f claims/lane$LANE
  # tasks still needing attempts, minus those claimed by the other lane and those excluded as persistent infra failures
  $PY $SRC/trial_status.py need $ORDER "jobs/wave-*" > claims/need.$LANE
  cat claims/lane* 2>/dev/null | sort -u > claims/taken.$LANE
  # persistent infra failures (MAX_INFRA infra attempts and still short) -> excluded, listed in excluded_infra.txt
  awk -v m=$MAX_INFRA '$3 >= m {print $1}' claims/need.$LANE >> excluded_infra.txt; sort -u -o excluded_infra.txt excluded_infra.txt
  pick=$(grep -vwF -f <(cat claims/taken.$LANE excluded_infra.txt; echo NONE) claims/need.$LANE | awk 'NR==1{n=$2} $2==n' | head -n $WAVE)
  if [ -z "$pick" ]; then flock -u 9; echo "$(date -Is) lane$LANE nothing left to claim"; [ -z "$(cat claims/lane* 2>/dev/null)" ] && break; sleep 300; continue; fi
  need=$(echo "$pick" | head -1 | awk '{print $2}')
  echo "$pick" | awk '{print $1}' > claims/lane$LANE
  flock -u 9
  name=$(printf "wave-%s-l%s" "$(date +%m%d-%H%M%S)" "$LANE"); dir=waves/$name; mkdir -p $dir
  for t in $(cat claims/lane$LANE); do ln -sfn $HERE/harbor_tasks/mimo-code/$t $dir/$t; done
  echo "$(date -Is) lane$LANE start $name: $(wc -l < claims/lane$LANE) tasks x $need attempts"
  K_ATTEMPTS=$need N_CONCURRENT=$NC MIMO_RUN_ID=scored $SRC/run_harbor.sh $dir $name \
    -r 2 --retry-include SandboxBuildFailedError --retry-include EnvironmentStartTimeoutError \
    --retry-include HealthcheckError --retry-include AgentSetupTimeoutError --retry-include DaytonaError \
    > logs/$name.log 2>&1
  echo "$(date -Is) lane$LANE done $name (exit $?): $($PY $SRC/trial_status.py summary jobs/$name | head -1)"
done
rm -f claims/lane$LANE
echo "$(date -Is) lane$LANE exiting"
